url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "paradone" # the name of your site, e.g. ACME Corp.
description: "paradigms for getting things done"